theme: jekyll-theme-minimal
logo: images/Guillaume.png
github:
  is_project_page: false
description:
github_username: guillaumedelaloy
social-network-links:
  linkedin: guillaume-delaloy-5187bbb2

share-links-active:
  linkedin: true
